import { defineConfig } from "vite";
import { resolve } from "path";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  root: ".",
  base: "/",
  publicDir: "public",
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        // Primary Pages
        resume: resolve(__dirname, "pages/resume.html"),
        gallery: resolve(__dirname, "pages/gallery.html"),
        blog: resolve(__dirname, "pages/blog.html"),
        music: resolve(__dirname, "pages/music.html"),
        tools: resolve(__dirname, "pages/tools.html"),
        "github-projects": resolve(__dirname, "pages/github-projects.html"),
        "mermaid-tool": resolve(__dirname, "pages/mermaid-tool.html"),
        notes: resolve(__dirname, "pages/notes.html"),
        reader: resolve(__dirname, "pages/reader.html"),
        thermodynamics: resolve(__dirname, "pages/thermodynamics.html"),

        // Tool Pages
        "audio-studio": resolve(__dirname, "pages/tools/audio-studio.html"),
        "equation-balancer": resolve(
          __dirname,
          "pages/tools/equation-balancer.html",
        ),
        games: resolve(__dirname, "pages/tools/games.html"),
        "llm-chat": resolve(__dirname, "pages/tools/llm-chat.html"),
        "llm-studio": resolve(__dirname, "pages/tools/llm-studio.html"),
        "mol-weight": resolve(__dirname, "pages/tools/mol-weight.html"),
        "molecule-viz": resolve(__dirname, "pages/tools/molecule-viz.html"),
        "paper-finder": resolve(__dirname, "pages/tools/paper-finder.html"),
        "pdf-reducer": resolve(__dirname, "pages/tools/pdf-reducer.html"),
        "pdf-studio": resolve(__dirname, "pages/tools/pdf-studio.html"),
        "pdf-to-jpg": resolve(__dirname, "pages/tools/pdf-to-jpg.html"),
        "periodic-table": resolve(__dirname, "pages/tools/periodic-table.html"),
        "ph-calculator": resolve(__dirname, "pages/tools/ph-calculator.html"),
        "unit-converter": resolve(__dirname, "pages/tools/unit-converter.html"),
        "youtube-downloader": resolve(
          __dirname,
          "pages/tools/youtube-downloader.html",
        ),
        "webcam-tester": resolve(__dirname, "pages/tools/webcam-tester.html"),
        playground: resolve(__dirname, "pages/tools/playground.html"),
        "file-share": resolve(__dirname, "pages/tools/file-share.html"),
        "image-studio": resolve(__dirname, "pages/tools/image-studio.html"),
        "fullscreen-timer": resolve(
          __dirname,
          "pages/tools/fullscreen-timer.html",
        ),

        // Public APIs directory (generated by scripts/generate-apis-pages.js)
        apis: resolve(__dirname, "pages/apis.html"),
        "apis-animals": resolve(__dirname, "pages/apis/animals.html"),
        "apis-anime": resolve(__dirname, "pages/apis/anime.html"),
        "apis-anti-malware": resolve(__dirname, "pages/apis/anti-malware.html"),
        "apis-art-and-design": resolve(
          __dirname,
          "pages/apis/art-and-design.html",
        ),
        "apis-blockchain": resolve(__dirname, "pages/apis/blockchain.html"),
        "apis-books": resolve(__dirname, "pages/apis/books.html"),
        "apis-business": resolve(__dirname, "pages/apis/business.html"),
        "apis-calendar": resolve(__dirname, "pages/apis/calendar.html"),
        "apis-cloud-storage-and-file-sharing": resolve(
          __dirname,
          "pages/apis/cloud-storage-and-file-sharing.html",
        ),
        "apis-cryptocurrency": resolve(
          __dirname,
          "pages/apis/cryptocurrency.html",
        ),
        "apis-currency-exchange": resolve(
          __dirname,
          "pages/apis/currency-exchange.html",
        ),
        "apis-data-validation": resolve(
          __dirname,
          "pages/apis/data-validation.html",
        ),
        "apis-development": resolve(__dirname, "pages/apis/development.html"),
        "apis-dictionaries": resolve(__dirname, "pages/apis/dictionaries.html"),
        "apis-documents-and-productivity": resolve(
          __dirname,
          "pages/apis/documents-and-productivity.html",
        ),
        "apis-email": resolve(__dirname, "pages/apis/email.html"),
        "apis-entertainment": resolve(
          __dirname,
          "pages/apis/entertainment.html",
        ),
        "apis-environment": resolve(__dirname, "pages/apis/environment.html"),
        "apis-finance": resolve(__dirname, "pages/apis/finance.html"),
        "apis-food-and-drink": resolve(
          __dirname,
          "pages/apis/food-and-drink.html",
        ),
        "apis-games-and-comics": resolve(
          __dirname,
          "pages/apis/games-and-comics.html",
        ),
        "apis-geocoding": resolve(__dirname, "pages/apis/geocoding.html"),
        "apis-government": resolve(__dirname, "pages/apis/government.html"),
        "apis-health": resolve(__dirname, "pages/apis/health.html"),
        "apis-jobs": resolve(__dirname, "pages/apis/jobs.html"),
        "apis-machine-learning": resolve(
          __dirname,
          "pages/apis/machine-learning.html",
        ),
        "apis-music": resolve(__dirname, "pages/apis/music.html"),
        "apis-news": resolve(__dirname, "pages/apis/news.html"),
        "apis-open-data": resolve(__dirname, "pages/apis/open-data.html"),
        "apis-open-source-projects": resolve(
          __dirname,
          "pages/apis/open-source-projects.html",
        ),
        "apis-patent": resolve(__dirname, "pages/apis/patent.html"),
        "apis-personality": resolve(__dirname, "pages/apis/personality.html"),
        "apis-phone": resolve(__dirname, "pages/apis/phone.html"),
        "apis-photography": resolve(__dirname, "pages/apis/photography.html"),
        "apis-programming": resolve(__dirname, "pages/apis/programming.html"),
        "apis-science-and-math": resolve(
          __dirname,
          "pages/apis/science-and-math.html",
        ),
        "apis-security": resolve(__dirname, "pages/apis/security.html"),
        "apis-shopping": resolve(__dirname, "pages/apis/shopping.html"),
        "apis-social": resolve(__dirname, "pages/apis/social.html"),
        "apis-sports-and-fitness": resolve(
          __dirname,
          "pages/apis/sports-and-fitness.html",
        ),
        "apis-test-data": resolve(__dirname, "pages/apis/test-data.html"),
        "apis-text-analysis": resolve(
          __dirname,
          "pages/apis/text-analysis.html",
        ),
        "apis-tracking": resolve(__dirname, "pages/apis/tracking.html"),
        "apis-transportation": resolve(
          __dirname,
          "pages/apis/transportation.html",
        ),
        "apis-url-shorteners": resolve(
          __dirname,
          "pages/apis/url-shorteners.html",
        ),
        "apis-vehicle": resolve(__dirname, "pages/apis/vehicle.html"),
        "apis-video": resolve(__dirname, "pages/apis/video.html"),
        "apis-weather": resolve(__dirname, "pages/apis/weather.html"),
      },
    },

    minify: "esbuild",
    sourcemap: false,
    assetsInlineLimit: 4096,
    // Measured 2026-09-18 (after making mermaid a lazy import in
    // src/mermaid-tool/components/Preview.jsx, which cut the editor entry
    // chunk from 880 kB to 253 kB):
    //   cynefin 675 kB, mermaid.core 621 kB — both THIRD-PARTY engines that
    //   load on demand, only when that diagram type is rendered; they cannot
    //   be shrunk without dropping diagram support. Our own largest chunk is
    //   253 kB.
    // 700 kB keeps the guard meaningful: any chunk we produce that grows past
    // it (or a further third-party regression) trips the warning again.
    chunkSizeWarningLimit: 700,
  },
  server: {
    port: 8080,
    host: true,
    open: true,
    fs: {
      // Allow serving files from parent directory (for symlinked assets)
      allow: [".."],
      strict: false,
    },
  },
  preview: {
    port: 8080,
    host: true,
    open: "pages/mermaid-tool.html",
  },
  resolve: {
    preserveSymlinks: true,
  },
});
